### ISSUE TITLE
Unable to use a freshly-built bundle

### ISSUE THREAD

**Issue by rm-dr** [tectonic-typesetting/tectonic-texlive-bundles#13]
I'm trying to build a set of texlive bundles using the documented commands:
```bash
./driver.sh build-image
./driver.sh update-containers
./driver.sh make-installation bundles/tlextras
./driver.sh install-packages bundles/tlextras
./driver.sh make-zipfile bundles/tlextras
./driver.sh make-itar bundles/tlextras
```

I'm building against Texlive 2022 (`tags/texlive-2022.0` in the git repo)

They all complete successfully, but tectonic refuses to compile latex documents using the bundle. With the V2 interface, the following `Texlive.toml` works:

```toml
[doc]
name = "Test"
bundle = "https://data1.fullyjustified.net/tlextras-2022.0r0.tar"

[[output]]
name = "main"
type = "pdf"
```

And the one below doesn't, failing with the following error. `test/formats.py` also fails for the same reason.

```toml
[doc]
name = "Test"
bundle = "file:///REDACTED/tectonic-texlive-bundles/state/artifacts/tlextras-2022.0r0/tlextras-2022.0r0.zip"

[[output]]
name = "main"
type = "pdf"
```
```
error: latex.ltx:10583: Undefined control sequence
error: halted on potentially-recoverable error as specified
```

I'm using tectonic `0.14.1`.
What's going on?
